keys:
  - &enkidu age1kpd52zhppnhypmfp26gxttk5j08n8gvwgxyt9xjj3c9wzff65uuqsrws8l
  - &wall-e age1hnn643wutt0lalz5njjrhhertst5h0nersuxmz37awel8je6n30qfalhcz

creation_rules:
  - path_regex: secrets/wall-e\.yaml$
    key_groups:
      - age:
          - *enkidu
          - *wall-e
