# Hardware configuration for enkidu (Framework laptop)
# Originally generated by 'nixos-generate-config'
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ xpadneo ];
  boot.initrd.kernelModules = [ ];
  boot.supportedFilesystems = [ "ntfs" ];
  boot.kernelModules = [ "kvm-intel" "v4l2loopback" ];
  boot.kernelParams = [ "module_blacklist=hid_sensor_hub" "resume_offset=155127808" ];

  # Laptop power management
  services.thermald.enable = true;
  services.power-profiles-daemon.enable = true;
  services.auto-cpufreq.enable = false;
  services.auto-cpufreq.settings = {
    battery = {
      governor = "powersave";
      turbo = "never";
    };
    charger = {
      governor = "performance";
      turbo = "auto";
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5b4b2bc5-27f3-4ff1-956c-d018b64ffa89";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/af768447-b9e4-4faa-b4e3-f46e351f0885";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EAFB-9188";
    fsType = "vfat";
  };

  # Set up deep sleep + hibernation
  swapDevices = [
    { device = "/var/swap"; }
  ];
  boot.resumeDevice = "/dev/disk/by-uuid/5b4b2bc5-27f3-4ff1-956c-d018b64ffa89";

  powerManagement = {
    powertop.enable = true;
  };

  networking.useDHCP = lib.mkDefault true;

  hardware.bluetooth.enable = true;
  hardware.enableRedistributableFirmware = true;

  hardware.graphics.extraPackages = with pkgs; [
    mesa
    intel-vaapi-driver
    libva-vdpau-driver
    intel-media-driver
  ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
